name: my first workflow

on: push

jobs:
    first_job:
        runs-on: ubuntu-latest
        steps:
            - name: checkout Repo
              uses: actions/checkout@v4
              
            - name: list and read files
              run: |
                echo "my first github action"
                ls -lrta
                cat README.md
            - name: Generate ASCII Contents
              run: cowsay -f dragon "Run for cover, I am a dragon ... RAWR" >> dragon.txt
            # - name: list files
            #   run: ls

            # - name: read file
            #   run: cat README.md