name: generate ascii code
on: push

jobs:
    first_job:
        runs-on: ubuntu-latest
        steps:
            - name: checkout Repo
              uses: actions/checkout@v4

            - name: list file repo
              run: ls -lrta
              
            - name: executing shell script
              run: ./ascii-script.sh


